### ISSUE TITLE
Feature extraction from frames

### ISSUE THREAD

**Issue by Abhiram4572** [shinying/dest#1]
Hi
Firstly, thanks for the code release.
I see that you have extracted frames from the video and stored them separately. 
However, extracting features from Video swin transformer is not clear (as it is reading videos but not frames)
Can you please provide detailed documentation on how to extract features from frames using the Video swin transformer?
Thanks!

**Comment by shinying** [comment]
Please read the README ([here](https://github.com/shinying/dest#video-features)), which brings you to [another repo](https://github.com/shinying/Video-Swin-Transformer). I extract video features from videos with the Video Swin Transformer.

**Comment by Abhiram4572** [comment]
Is there a way to extract from frames instead of videos?

**Comment by shinying** [comment]
You can first create videos from frames with, for example, [ffmpeg](https://trac.ffmpeg.org/wiki/Slideshow).
